Some common terms: 
-Corpus
-Vocabulary
-Document
-Word

BAG OF WORDS

In [2]:
import numpy as np
import pandas as pd 

In [3]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

In [8]:
bow =  cv.fit_transform(df['text'])

In [9]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comment': 0}


In [12]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [14]:
cv.transform(['Bappy watch dswithbappy']).toarray()

array([[0, 1, 0, 1, 0]])

In [16]:
X = bow.toarray()
y = df['output']
X,y

(array([[0, 1, 1, 1, 0],
        [0, 2, 0, 1, 0],
        [1, 0, 1, 0, 1],
        [1, 1, 0, 0, 1]]),
 0    1
 1    1
 2    0
 3    0
 Name: output, dtype: int64)

N-GRAMS